name: 'RSS Git Scraper'
description: 'Scrape a website and generate RSS feed with git history'
author: 'Your Name'

inputs:
  url:
    description: 'URL to scrape'
    required: true
  feed_name:
    description: 'Name for the RSS feed (e.g., "jank-progress")'
    required: true
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash
    
    - name: Install dependencies
      run: |
        uv sync
      shell: bash
      working-directory: ${{ github.action_path }}
    
    - name: Run scraper
      id: scrape
      run: |
        uv run python main.py "${{ inputs.url }}" "${{ inputs.feed_name }}"
      shell: bash
      working-directory: ${{ github.action_path }}
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add all changes
        git add feeds/ content/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update ${{ inputs.feed_name }}: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push
        fi
      shell: bash