# Example sites.toml configuration
# Copy this file to your repository and customize it

# Each [[sites]] section defines a website to track
[[sites]]
url = "https://example.com/blog"      # The URL to monitor
feed_name = "example-blog"            # Name for the RSS feed (alphanumeric + hyphens)
min_hours = 12                        # Optional: Only check every 12 hours

[[sites]]
url = "https://news.ycombinator.com"
feed_name = "hackernews"
# No min_hours = check every time the action runs

[[sites]]
url = "https://blog.rust-lang.org/"
feed_name = "rust-blog"
min_hours = 24                        # Only check once per day

# Add as many sites as you want
[[sites]]
url = "https://changelog.your-app.com"
feed_name = "app-changelog"
min_hours = 168                       # Weekly (168 hours)

# Status pages might need frequent checks
[[sites]]
url = "https://status.github.com"
feed_name = "status-github"
min_hours = 0.5                       # Every 30 minutes

[[sites]]
url = "https://status.openai.com"
feed_name = "status-openai"
# No min_hours = check every 4 hours (or whatever your cron is)