name: Monitor Sites and Update RSS Feeds

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:        # Allow manual triggering

jobs:
  monitor-sites:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # Check out your repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Install the watcher package
      - name: Install watcher
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/gpwclark/watcher.git
      
      # Run the monitoring
      - name: Monitor sites
        run: |
          # GitHub URLs for RSS feed links
          BASE_URL="https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}"
          
          # Process all sites in sites.toml
          watcher-batch --config sites.toml --base-url "$BASE_URL"
      
      # Commit any changes
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          
          git add feeds/ content/ || true
          
          if git diff --staged --quiet; then
            echo "No changes detected"
          else
            git commit -m "Update feeds: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi

# QUICK START:
# 
# 1. Create a sites.toml file in your repository root:
#    
#    [[sites]]
#    url = "https://example.com"
#    feed_name = "example"
#    min_hours = 1.0  # Optional: minimum hours between checks
#
# 2. Copy this workflow to .github/workflows/monitor-sites.yml
#
# 3. Push to GitHub - the workflow will run automatically
#
# 4. Access your RSS feeds at:
#    https://github.com/YOUR_USERNAME/YOUR_REPO/blob/main/feeds/
#
# 5. View history with diffs at:
#    https://github.com/YOUR_USERNAME/YOUR_REPO/blob/main/content/history-explorer.html
