# Watcher Sites Configuration
# Add your sites to track here

[[sites]]
url = "https://jank-lang.org/progress/"
feed_name = "jank-progress"
min_hours = 24  # Check once a day

[[sites]]
url = "https://www.timeanddate.com/counters/newyear.html"
feed_name = "example-changelog2"

[[sites]]
url = "https://www.timeanddate.com/counters/newyear.html"
feed_name = "example-changelog"

[[sites]]
url = "https://www.cisa.gov/news-events/news"
feed_name = "cisa-gov-news"

[[sites]]
url = "https://disa.mil/NewsandEvents"
feed_name = "disa-mil-news"
