[[watcher.sites]]
url = "https://jank-lang.org/progress/"
feed_name = "jank-progress"
min_hours = 24  # Check once a day
# exclude_tags = ["script", "style", "nav", "header", "footer"]  # Default tags excluded

[[watcher.sites]]
url = "https://www.timeanddate.com/counters/newyear.html"
feed_name = "example-changelog2"

[[watcher.sites]]
url = "https://www.timeanddate.com/counters/newyear.html"
feed_name = "example-changelog"

[[watcher.sites]]
url = "https://www.nih.gov/news-events/news-releases"
feed_name = "nih-news"
# Example: Also exclude aside and form elements for this site
# exclude_tags = ["script", "style", "nav", "header", "footer", "aside", "form"]

[[watcher.sites]]
url = "https://disa.mil/NewsandEvents"
feed_name = "disa-mil-news"

[[watcher.sites]]
url = "https://www.dni.gov/index.php/newsroom/press-releases"
feed_name = "odni"

[[watcher.sites]]
url = "https://www.cisa.gov/news-events/news"
feed_name = "cisa-gov-news"

