name: Python Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Build and test watcher"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Flox"
        uses: "flox/install-flox-action@v2"

      - name: "Activate Flox and run lint/format"
        run: |
          flox activate -- just install
          flox activate -- just check

      - name: "Run pytest with Flox"
        run: |
          flox activate -- just test
