name: Scrape Jank Lang Progress

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Scrape Jank Lang Progress
        uses: ./
        with:
          url: https://jank-lang.org/progress/
          feed_name: jank-progress